# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NmJkYjgyYTQ4YTMzN2M5NDgwY2RhOWQ0ZGRkNDY4OWJhZTFhOGVjNGMxMGQxZTc4MjkzZjgxMjEyNTRkNGIyYzE4ZjRmMjg4NjZmMTc4OWI4ZjkyOWVkNWMwYWVhMTY4ZjBhZjBkMWFkYjA1ZjlhNDNmZTQ1MTA1ZGU2YTYxM2E=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
